version: '3.9'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "8080:8080"